apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: example-app-sa
roleRef:
  kind: Role
  name: example-app-role
  apiGroup: rbac.authorization.k8s.io
